name: CI

on:
  push:
    branches: [main, ci-*]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm run lint:format
      - run: npm run lint
  test:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18', '20', '22.4.x']
    name: Testing on node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build:cli
      - run: npm run link
      - name: Clone and index templates
        run: myst-templates-api index data/tex.yml data/docx.yml data/site.yml data/typst.yml
      - run: npm run test
